name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-ci:
    runs-on: ubuntu-22.04
    env:
      working-directory: newquiz

    steps: 
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'


    - name: make application-secret.yml
      run: |
        touch ./src/main/resources/application-secret.yml
        echo "${{ secrets.APPLICATION_SECRET }}" > ./src/main/resources/application-secret.yml
      shell: bash

    - name: Generate news-categorize-prompt.txt
      run: |
        cat <<EOF > ./src/main/resources/news-categorize-prompt.txt
        ${{ secrets.NEWS_CATEGORIZE_PROMPT }}
        EOF
      shell: bash

    - name: Generate quiz-generation-prompt.txt
      run: |
        cat <<EOF > ./src/main/resources/quiz-generate-prompt.txt
        ${{ secrets.QUIZ_GENERATE_PROMPT }}
        EOF
      shell: bash

    - name: Generate summary-feedback-prompt.txt
      run: |
        cat <<EOF > ./src/main/resources/summary-feedback-prompt.txt
        ${{ secrets.SUMMARY_FEEDBACK_PROMPT }}
        EOF
      shell: bash

    - name: 빌드
      run: |
          chmod +x gradlew
          ./gradlew build -x test
      shell: bash

    - name: docker build 가능하도록 환경 설정
      uses: docker/setup-buildx-action@v2.9.1
      
    - name: docker hub에로그인
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKERHUB_LOGIN_USERNAME }}
        password: ${{ secrets.DOCKERHUB_LOGIN_ACCESSTOKEN }}

    - name: docker image 빌드 및 푸시
      run: |
        docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_LOGIN_USERNAME }}/${{ secrets.DOCKERHUB_LOGIN_USERNAME }} .
        docker push ${{ secrets.DOCKERHUB_LOGIN_USERNAME }}/${{ secrets.DOCKERHUB_LOGIN_USERNAME }}

  deploy-cd:      
    needs: deploy-ci
    runs-on: ubuntu-22.04
    steps:
    - name: 도커 컨테이너 실행
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.RELEASE_HOST }}
        username: ${{ secrets.RELEASE_USERNAME }}
        key: ${{ secrets.RELEASE_KEY }}
        script: |
          sudo chmod +x /home/ubuntu/deploy.sh
          sudo /home/ubuntu/deploy.sh      
